language: node_js
node_js:
  - node

cache:
  directories:
    - 'node_modules'

services:
  - mongodb

before_script:
  # Install npm dependencies
  - npm ci
  - sleep 15

script:
  - 'npm run start:prod'
