language: node_js
node_js:
  - node

cache:
  directories:
    - 'node_modules'

services:
  - mongodb

before_install:
  - npm i -g npm@latest

install:
  # Install npm dependencies
  - npm ci
  # Build server
  - npm run build

jobs:
  include:
    - stage: test
      name: 'Unit Tests'
      script: npm run test
    - stage: test_two
      name: 'e2e Tests'
      script: npm run test:e2e
